#!/bin/sh

PROJECT=fgosite

if [ $# != 2 ]; then
    echo "USAGE:    $0 target tag"
    exit 1
fi
target=$1
tag=$2

dir=/tmp/deploy-$PROJECT-$$
mkdir -p $dir

set -x
cd $dir
git clone git@github.com:eobrain/$PROJECT.git
cd $PROJECT
git pull --tags
git checkout $tag
git status

cmd="make VERSION=$tag $target"
read -p "<ENTER> to '$cmd', or <CTRL>-C to abort" dummy
$cmd
