#!/bin/bash -x

SDK=$HOME/installations/appengine-java-sdk-1.9.2

lein do  fgoc,  cljsbuild once,  ring uberwar

war=`ls -tr target/*-standalone.war | tail -1`
unzip $war -d /tmp/open-war-$$

$SDK/bin/dev_appserver.sh /tmp/open-war-$$
